import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen w-screen flex flex-col justify-between items-center bg-[#F4F4F4] ">
          <main className="max-w-[80ch] pt-24 relative px-8 mx-auto w-full  min-h-screen border border-gray-300 border-dashed">
            {children}
          <Footer></Footer>
          </main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
